[project]
name = "document-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.27.2",
]

[project.scripts]
document-extractor = "document_extractor.cli:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
